version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # host:container
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # host:container
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development