/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginPageRouteImport } from './routes/login/page'
import { Route as UAPSUAPSRouteImport } from './routes/UAPS/UAPS'
import { Route as UAPSPROFILEESuivreRouteImport } from './routes/UAPS/PROFILEE/suivre'
import { Route as UAPSPROFILEEModifierRouteImport } from './routes/UAPS/PROFILEE/modifier'
import { Route as UAPSPROFILEEJournalierRouteImport } from './routes/UAPS/PROFILEE/journalier'
import { Route as UAPSPROFILEEImporterRouteImport } from './routes/UAPS/PROFILEE/importer'
import { Route as UAPSPROFILEEHistoriqueRouteImport } from './routes/UAPS/PROFILEE/historique'
import { Route as UAPSPROFILEEHebdomadaireRouteImport } from './routes/UAPS/PROFILEE/hebdomadaire'
import { Route as UAPSPROFILEEPROFILEERouteImport } from './routes/UAPS/PROFILEE/PROFILEE'
import { Route as UAPSPDIMSuivreRouteImport } from './routes/UAPS/P-DIM/suivre'
import { Route as UAPSPDIMModifierRouteImport } from './routes/UAPS/P-DIM/modifier'
import { Route as UAPSPDIMJournalierRouteImport } from './routes/UAPS/P-DIM/journalier'
import { Route as UAPSPDIMImporterRouteImport } from './routes/UAPS/P-DIM/importer'
import { Route as UAPSPDIMHistoriqueRouteImport } from './routes/UAPS/P-DIM/historique'
import { Route as UAPSPDIMHebdomadaireRouteImport } from './routes/UAPS/P-DIM/hebdomadaire'
import { Route as UAPSPDIMPDIMRouteImport } from './routes/UAPS/P-DIM/P-DIM'
import { Route as UAPSGDIMSuivreRouteImport } from './routes/UAPS/G-DIM/suivre'
import { Route as UAPSGDIMModifierRouteImport } from './routes/UAPS/G-DIM/modifier'
import { Route as UAPSGDIMJournalierRouteImport } from './routes/UAPS/G-DIM/journalier'
import { Route as UAPSGDIMImporterRouteImport } from './routes/UAPS/G-DIM/importer'
import { Route as UAPSGDIMHistoriqueRouteImport } from './routes/UAPS/G-DIM/historique'
import { Route as UAPSGDIMHebdomadaireRouteImport } from './routes/UAPS/G-DIM/hebdomadaire'
import { Route as UAPSGDIMGDIMRouteImport } from './routes/UAPS/G-DIM/G-DIM'
import { Route as UAPSPROFILEEValidationProductionRouteImport } from './routes/UAPS/PROFILEE/Validation/production'
import { Route as UAPSPROFILEEValidationOutillageRouteImport } from './routes/UAPS/PROFILEE/Validation/outillage'
import { Route as UAPSPROFILEEValidationMatiereRouteImport } from './routes/UAPS/PROFILEE/Validation/matiere'
import { Route as UAPSPDIMValidationProductionRouteImport } from './routes/UAPS/P-DIM/Validation/production'
import { Route as UAPSPDIMValidationOutillageRouteImport } from './routes/UAPS/P-DIM/Validation/outillage'
import { Route as UAPSPDIMValidationMatiereRouteImport } from './routes/UAPS/P-DIM/Validation/matiere'
import { Route as UAPSGDIMValidationProductionRouteImport } from './routes/UAPS/G-DIM/Validation/production'
import { Route as UAPSGDIMValidationOutillageRouteImport } from './routes/UAPS/G-DIM/Validation/outillage'
import { Route as UAPSGDIMValidationMatiereRouteImport } from './routes/UAPS/G-DIM/Validation/matiere'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPageRoute = LoginPageRouteImport.update({
  id: '/login/page',
  path: '/login/page',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSUAPSRoute = UAPSUAPSRouteImport.update({
  id: '/UAPS/UAPS',
  path: '/UAPS/UAPS',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEESuivreRoute = UAPSPROFILEESuivreRouteImport.update({
  id: '/UAPS/PROFILEE/suivre',
  path: '/UAPS/PROFILEE/suivre',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEEModifierRoute = UAPSPROFILEEModifierRouteImport.update({
  id: '/UAPS/PROFILEE/modifier',
  path: '/UAPS/PROFILEE/modifier',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEEJournalierRoute = UAPSPROFILEEJournalierRouteImport.update({
  id: '/UAPS/PROFILEE/journalier',
  path: '/UAPS/PROFILEE/journalier',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEEImporterRoute = UAPSPROFILEEImporterRouteImport.update({
  id: '/UAPS/PROFILEE/importer',
  path: '/UAPS/PROFILEE/importer',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEEHistoriqueRoute = UAPSPROFILEEHistoriqueRouteImport.update({
  id: '/UAPS/PROFILEE/historique',
  path: '/UAPS/PROFILEE/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEEHebdomadaireRoute =
  UAPSPROFILEEHebdomadaireRouteImport.update({
    id: '/UAPS/PROFILEE/hebdomadaire',
    path: '/UAPS/PROFILEE/hebdomadaire',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSPROFILEEPROFILEERoute = UAPSPROFILEEPROFILEERouteImport.update({
  id: '/UAPS/PROFILEE/PROFILEE',
  path: '/UAPS/PROFILEE/PROFILEE',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMSuivreRoute = UAPSPDIMSuivreRouteImport.update({
  id: '/UAPS/P-DIM/suivre',
  path: '/UAPS/P-DIM/suivre',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMModifierRoute = UAPSPDIMModifierRouteImport.update({
  id: '/UAPS/P-DIM/modifier',
  path: '/UAPS/P-DIM/modifier',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMJournalierRoute = UAPSPDIMJournalierRouteImport.update({
  id: '/UAPS/P-DIM/journalier',
  path: '/UAPS/P-DIM/journalier',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMImporterRoute = UAPSPDIMImporterRouteImport.update({
  id: '/UAPS/P-DIM/importer',
  path: '/UAPS/P-DIM/importer',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMHistoriqueRoute = UAPSPDIMHistoriqueRouteImport.update({
  id: '/UAPS/P-DIM/historique',
  path: '/UAPS/P-DIM/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMHebdomadaireRoute = UAPSPDIMHebdomadaireRouteImport.update({
  id: '/UAPS/P-DIM/hebdomadaire',
  path: '/UAPS/P-DIM/hebdomadaire',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPDIMPDIMRoute = UAPSPDIMPDIMRouteImport.update({
  id: '/UAPS/P-DIM/P-DIM',
  path: '/UAPS/P-DIM/P-DIM',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMSuivreRoute = UAPSGDIMSuivreRouteImport.update({
  id: '/UAPS/G-DIM/suivre',
  path: '/UAPS/G-DIM/suivre',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMModifierRoute = UAPSGDIMModifierRouteImport.update({
  id: '/UAPS/G-DIM/modifier',
  path: '/UAPS/G-DIM/modifier',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMJournalierRoute = UAPSGDIMJournalierRouteImport.update({
  id: '/UAPS/G-DIM/journalier',
  path: '/UAPS/G-DIM/journalier',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMImporterRoute = UAPSGDIMImporterRouteImport.update({
  id: '/UAPS/G-DIM/importer',
  path: '/UAPS/G-DIM/importer',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMHistoriqueRoute = UAPSGDIMHistoriqueRouteImport.update({
  id: '/UAPS/G-DIM/historique',
  path: '/UAPS/G-DIM/historique',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMHebdomadaireRoute = UAPSGDIMHebdomadaireRouteImport.update({
  id: '/UAPS/G-DIM/hebdomadaire',
  path: '/UAPS/G-DIM/hebdomadaire',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSGDIMGDIMRoute = UAPSGDIMGDIMRouteImport.update({
  id: '/UAPS/G-DIM/G-DIM',
  path: '/UAPS/G-DIM/G-DIM',
  getParentRoute: () => rootRouteImport,
} as any)
const UAPSPROFILEEValidationProductionRoute =
  UAPSPROFILEEValidationProductionRouteImport.update({
    id: '/UAPS/PROFILEE/Validation/production',
    path: '/UAPS/PROFILEE/Validation/production',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSPROFILEEValidationOutillageRoute =
  UAPSPROFILEEValidationOutillageRouteImport.update({
    id: '/UAPS/PROFILEE/Validation/outillage',
    path: '/UAPS/PROFILEE/Validation/outillage',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSPROFILEEValidationMatiereRoute =
  UAPSPROFILEEValidationMatiereRouteImport.update({
    id: '/UAPS/PROFILEE/Validation/matiere',
    path: '/UAPS/PROFILEE/Validation/matiere',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSPDIMValidationProductionRoute =
  UAPSPDIMValidationProductionRouteImport.update({
    id: '/UAPS/P-DIM/Validation/production',
    path: '/UAPS/P-DIM/Validation/production',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSPDIMValidationOutillageRoute =
  UAPSPDIMValidationOutillageRouteImport.update({
    id: '/UAPS/P-DIM/Validation/outillage',
    path: '/UAPS/P-DIM/Validation/outillage',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSPDIMValidationMatiereRoute =
  UAPSPDIMValidationMatiereRouteImport.update({
    id: '/UAPS/P-DIM/Validation/matiere',
    path: '/UAPS/P-DIM/Validation/matiere',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSGDIMValidationProductionRoute =
  UAPSGDIMValidationProductionRouteImport.update({
    id: '/UAPS/G-DIM/Validation/production',
    path: '/UAPS/G-DIM/Validation/production',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSGDIMValidationOutillageRoute =
  UAPSGDIMValidationOutillageRouteImport.update({
    id: '/UAPS/G-DIM/Validation/outillage',
    path: '/UAPS/G-DIM/Validation/outillage',
    getParentRoute: () => rootRouteImport,
  } as any)
const UAPSGDIMValidationMatiereRoute =
  UAPSGDIMValidationMatiereRouteImport.update({
    id: '/UAPS/G-DIM/Validation/matiere',
    path: '/UAPS/G-DIM/Validation/matiere',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/UAPS/UAPS': typeof UAPSUAPSRoute
  '/login/page': typeof LoginPageRoute
  '/UAPS/G-DIM/G-DIM': typeof UAPSGDIMGDIMRoute
  '/UAPS/G-DIM/hebdomadaire': typeof UAPSGDIMHebdomadaireRoute
  '/UAPS/G-DIM/historique': typeof UAPSGDIMHistoriqueRoute
  '/UAPS/G-DIM/importer': typeof UAPSGDIMImporterRoute
  '/UAPS/G-DIM/journalier': typeof UAPSGDIMJournalierRoute
  '/UAPS/G-DIM/modifier': typeof UAPSGDIMModifierRoute
  '/UAPS/G-DIM/suivre': typeof UAPSGDIMSuivreRoute
  '/UAPS/P-DIM/P-DIM': typeof UAPSPDIMPDIMRoute
  '/UAPS/P-DIM/hebdomadaire': typeof UAPSPDIMHebdomadaireRoute
  '/UAPS/P-DIM/historique': typeof UAPSPDIMHistoriqueRoute
  '/UAPS/P-DIM/importer': typeof UAPSPDIMImporterRoute
  '/UAPS/P-DIM/journalier': typeof UAPSPDIMJournalierRoute
  '/UAPS/P-DIM/modifier': typeof UAPSPDIMModifierRoute
  '/UAPS/P-DIM/suivre': typeof UAPSPDIMSuivreRoute
  '/UAPS/PROFILEE/PROFILEE': typeof UAPSPROFILEEPROFILEERoute
  '/UAPS/PROFILEE/hebdomadaire': typeof UAPSPROFILEEHebdomadaireRoute
  '/UAPS/PROFILEE/historique': typeof UAPSPROFILEEHistoriqueRoute
  '/UAPS/PROFILEE/importer': typeof UAPSPROFILEEImporterRoute
  '/UAPS/PROFILEE/journalier': typeof UAPSPROFILEEJournalierRoute
  '/UAPS/PROFILEE/modifier': typeof UAPSPROFILEEModifierRoute
  '/UAPS/PROFILEE/suivre': typeof UAPSPROFILEESuivreRoute
  '/UAPS/G-DIM/Validation/matiere': typeof UAPSGDIMValidationMatiereRoute
  '/UAPS/G-DIM/Validation/outillage': typeof UAPSGDIMValidationOutillageRoute
  '/UAPS/G-DIM/Validation/production': typeof UAPSGDIMValidationProductionRoute
  '/UAPS/P-DIM/Validation/matiere': typeof UAPSPDIMValidationMatiereRoute
  '/UAPS/P-DIM/Validation/outillage': typeof UAPSPDIMValidationOutillageRoute
  '/UAPS/P-DIM/Validation/production': typeof UAPSPDIMValidationProductionRoute
  '/UAPS/PROFILEE/Validation/matiere': typeof UAPSPROFILEEValidationMatiereRoute
  '/UAPS/PROFILEE/Validation/outillage': typeof UAPSPROFILEEValidationOutillageRoute
  '/UAPS/PROFILEE/Validation/production': typeof UAPSPROFILEEValidationProductionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/UAPS/UAPS': typeof UAPSUAPSRoute
  '/login/page': typeof LoginPageRoute
  '/UAPS/G-DIM/G-DIM': typeof UAPSGDIMGDIMRoute
  '/UAPS/G-DIM/hebdomadaire': typeof UAPSGDIMHebdomadaireRoute
  '/UAPS/G-DIM/historique': typeof UAPSGDIMHistoriqueRoute
  '/UAPS/G-DIM/importer': typeof UAPSGDIMImporterRoute
  '/UAPS/G-DIM/journalier': typeof UAPSGDIMJournalierRoute
  '/UAPS/G-DIM/modifier': typeof UAPSGDIMModifierRoute
  '/UAPS/G-DIM/suivre': typeof UAPSGDIMSuivreRoute
  '/UAPS/P-DIM/P-DIM': typeof UAPSPDIMPDIMRoute
  '/UAPS/P-DIM/hebdomadaire': typeof UAPSPDIMHebdomadaireRoute
  '/UAPS/P-DIM/historique': typeof UAPSPDIMHistoriqueRoute
  '/UAPS/P-DIM/importer': typeof UAPSPDIMImporterRoute
  '/UAPS/P-DIM/journalier': typeof UAPSPDIMJournalierRoute
  '/UAPS/P-DIM/modifier': typeof UAPSPDIMModifierRoute
  '/UAPS/P-DIM/suivre': typeof UAPSPDIMSuivreRoute
  '/UAPS/PROFILEE/PROFILEE': typeof UAPSPROFILEEPROFILEERoute
  '/UAPS/PROFILEE/hebdomadaire': typeof UAPSPROFILEEHebdomadaireRoute
  '/UAPS/PROFILEE/historique': typeof UAPSPROFILEEHistoriqueRoute
  '/UAPS/PROFILEE/importer': typeof UAPSPROFILEEImporterRoute
  '/UAPS/PROFILEE/journalier': typeof UAPSPROFILEEJournalierRoute
  '/UAPS/PROFILEE/modifier': typeof UAPSPROFILEEModifierRoute
  '/UAPS/PROFILEE/suivre': typeof UAPSPROFILEESuivreRoute
  '/UAPS/G-DIM/Validation/matiere': typeof UAPSGDIMValidationMatiereRoute
  '/UAPS/G-DIM/Validation/outillage': typeof UAPSGDIMValidationOutillageRoute
  '/UAPS/G-DIM/Validation/production': typeof UAPSGDIMValidationProductionRoute
  '/UAPS/P-DIM/Validation/matiere': typeof UAPSPDIMValidationMatiereRoute
  '/UAPS/P-DIM/Validation/outillage': typeof UAPSPDIMValidationOutillageRoute
  '/UAPS/P-DIM/Validation/production': typeof UAPSPDIMValidationProductionRoute
  '/UAPS/PROFILEE/Validation/matiere': typeof UAPSPROFILEEValidationMatiereRoute
  '/UAPS/PROFILEE/Validation/outillage': typeof UAPSPROFILEEValidationOutillageRoute
  '/UAPS/PROFILEE/Validation/production': typeof UAPSPROFILEEValidationProductionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/UAPS/UAPS': typeof UAPSUAPSRoute
  '/login/page': typeof LoginPageRoute
  '/UAPS/G-DIM/G-DIM': typeof UAPSGDIMGDIMRoute
  '/UAPS/G-DIM/hebdomadaire': typeof UAPSGDIMHebdomadaireRoute
  '/UAPS/G-DIM/historique': typeof UAPSGDIMHistoriqueRoute
  '/UAPS/G-DIM/importer': typeof UAPSGDIMImporterRoute
  '/UAPS/G-DIM/journalier': typeof UAPSGDIMJournalierRoute
  '/UAPS/G-DIM/modifier': typeof UAPSGDIMModifierRoute
  '/UAPS/G-DIM/suivre': typeof UAPSGDIMSuivreRoute
  '/UAPS/P-DIM/P-DIM': typeof UAPSPDIMPDIMRoute
  '/UAPS/P-DIM/hebdomadaire': typeof UAPSPDIMHebdomadaireRoute
  '/UAPS/P-DIM/historique': typeof UAPSPDIMHistoriqueRoute
  '/UAPS/P-DIM/importer': typeof UAPSPDIMImporterRoute
  '/UAPS/P-DIM/journalier': typeof UAPSPDIMJournalierRoute
  '/UAPS/P-DIM/modifier': typeof UAPSPDIMModifierRoute
  '/UAPS/P-DIM/suivre': typeof UAPSPDIMSuivreRoute
  '/UAPS/PROFILEE/PROFILEE': typeof UAPSPROFILEEPROFILEERoute
  '/UAPS/PROFILEE/hebdomadaire': typeof UAPSPROFILEEHebdomadaireRoute
  '/UAPS/PROFILEE/historique': typeof UAPSPROFILEEHistoriqueRoute
  '/UAPS/PROFILEE/importer': typeof UAPSPROFILEEImporterRoute
  '/UAPS/PROFILEE/journalier': typeof UAPSPROFILEEJournalierRoute
  '/UAPS/PROFILEE/modifier': typeof UAPSPROFILEEModifierRoute
  '/UAPS/PROFILEE/suivre': typeof UAPSPROFILEESuivreRoute
  '/UAPS/G-DIM/Validation/matiere': typeof UAPSGDIMValidationMatiereRoute
  '/UAPS/G-DIM/Validation/outillage': typeof UAPSGDIMValidationOutillageRoute
  '/UAPS/G-DIM/Validation/production': typeof UAPSGDIMValidationProductionRoute
  '/UAPS/P-DIM/Validation/matiere': typeof UAPSPDIMValidationMatiereRoute
  '/UAPS/P-DIM/Validation/outillage': typeof UAPSPDIMValidationOutillageRoute
  '/UAPS/P-DIM/Validation/production': typeof UAPSPDIMValidationProductionRoute
  '/UAPS/PROFILEE/Validation/matiere': typeof UAPSPROFILEEValidationMatiereRoute
  '/UAPS/PROFILEE/Validation/outillage': typeof UAPSPROFILEEValidationOutillageRoute
  '/UAPS/PROFILEE/Validation/production': typeof UAPSPROFILEEValidationProductionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/UAPS/UAPS'
    | '/login/page'
    | '/UAPS/G-DIM/G-DIM'
    | '/UAPS/G-DIM/hebdomadaire'
    | '/UAPS/G-DIM/historique'
    | '/UAPS/G-DIM/importer'
    | '/UAPS/G-DIM/journalier'
    | '/UAPS/G-DIM/modifier'
    | '/UAPS/G-DIM/suivre'
    | '/UAPS/P-DIM/P-DIM'
    | '/UAPS/P-DIM/hebdomadaire'
    | '/UAPS/P-DIM/historique'
    | '/UAPS/P-DIM/importer'
    | '/UAPS/P-DIM/journalier'
    | '/UAPS/P-DIM/modifier'
    | '/UAPS/P-DIM/suivre'
    | '/UAPS/PROFILEE/PROFILEE'
    | '/UAPS/PROFILEE/hebdomadaire'
    | '/UAPS/PROFILEE/historique'
    | '/UAPS/PROFILEE/importer'
    | '/UAPS/PROFILEE/journalier'
    | '/UAPS/PROFILEE/modifier'
    | '/UAPS/PROFILEE/suivre'
    | '/UAPS/G-DIM/Validation/matiere'
    | '/UAPS/G-DIM/Validation/outillage'
    | '/UAPS/G-DIM/Validation/production'
    | '/UAPS/P-DIM/Validation/matiere'
    | '/UAPS/P-DIM/Validation/outillage'
    | '/UAPS/P-DIM/Validation/production'
    | '/UAPS/PROFILEE/Validation/matiere'
    | '/UAPS/PROFILEE/Validation/outillage'
    | '/UAPS/PROFILEE/Validation/production'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/UAPS/UAPS'
    | '/login/page'
    | '/UAPS/G-DIM/G-DIM'
    | '/UAPS/G-DIM/hebdomadaire'
    | '/UAPS/G-DIM/historique'
    | '/UAPS/G-DIM/importer'
    | '/UAPS/G-DIM/journalier'
    | '/UAPS/G-DIM/modifier'
    | '/UAPS/G-DIM/suivre'
    | '/UAPS/P-DIM/P-DIM'
    | '/UAPS/P-DIM/hebdomadaire'
    | '/UAPS/P-DIM/historique'
    | '/UAPS/P-DIM/importer'
    | '/UAPS/P-DIM/journalier'
    | '/UAPS/P-DIM/modifier'
    | '/UAPS/P-DIM/suivre'
    | '/UAPS/PROFILEE/PROFILEE'
    | '/UAPS/PROFILEE/hebdomadaire'
    | '/UAPS/PROFILEE/historique'
    | '/UAPS/PROFILEE/importer'
    | '/UAPS/PROFILEE/journalier'
    | '/UAPS/PROFILEE/modifier'
    | '/UAPS/PROFILEE/suivre'
    | '/UAPS/G-DIM/Validation/matiere'
    | '/UAPS/G-DIM/Validation/outillage'
    | '/UAPS/G-DIM/Validation/production'
    | '/UAPS/P-DIM/Validation/matiere'
    | '/UAPS/P-DIM/Validation/outillage'
    | '/UAPS/P-DIM/Validation/production'
    | '/UAPS/PROFILEE/Validation/matiere'
    | '/UAPS/PROFILEE/Validation/outillage'
    | '/UAPS/PROFILEE/Validation/production'
  id:
    | '__root__'
    | '/'
    | '/UAPS/UAPS'
    | '/login/page'
    | '/UAPS/G-DIM/G-DIM'
    | '/UAPS/G-DIM/hebdomadaire'
    | '/UAPS/G-DIM/historique'
    | '/UAPS/G-DIM/importer'
    | '/UAPS/G-DIM/journalier'
    | '/UAPS/G-DIM/modifier'
    | '/UAPS/G-DIM/suivre'
    | '/UAPS/P-DIM/P-DIM'
    | '/UAPS/P-DIM/hebdomadaire'
    | '/UAPS/P-DIM/historique'
    | '/UAPS/P-DIM/importer'
    | '/UAPS/P-DIM/journalier'
    | '/UAPS/P-DIM/modifier'
    | '/UAPS/P-DIM/suivre'
    | '/UAPS/PROFILEE/PROFILEE'
    | '/UAPS/PROFILEE/hebdomadaire'
    | '/UAPS/PROFILEE/historique'
    | '/UAPS/PROFILEE/importer'
    | '/UAPS/PROFILEE/journalier'
    | '/UAPS/PROFILEE/modifier'
    | '/UAPS/PROFILEE/suivre'
    | '/UAPS/G-DIM/Validation/matiere'
    | '/UAPS/G-DIM/Validation/outillage'
    | '/UAPS/G-DIM/Validation/production'
    | '/UAPS/P-DIM/Validation/matiere'
    | '/UAPS/P-DIM/Validation/outillage'
    | '/UAPS/P-DIM/Validation/production'
    | '/UAPS/PROFILEE/Validation/matiere'
    | '/UAPS/PROFILEE/Validation/outillage'
    | '/UAPS/PROFILEE/Validation/production'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UAPSUAPSRoute: typeof UAPSUAPSRoute
  LoginPageRoute: typeof LoginPageRoute
  UAPSGDIMGDIMRoute: typeof UAPSGDIMGDIMRoute
  UAPSGDIMHebdomadaireRoute: typeof UAPSGDIMHebdomadaireRoute
  UAPSGDIMHistoriqueRoute: typeof UAPSGDIMHistoriqueRoute
  UAPSGDIMImporterRoute: typeof UAPSGDIMImporterRoute
  UAPSGDIMJournalierRoute: typeof UAPSGDIMJournalierRoute
  UAPSGDIMModifierRoute: typeof UAPSGDIMModifierRoute
  UAPSGDIMSuivreRoute: typeof UAPSGDIMSuivreRoute
  UAPSPDIMPDIMRoute: typeof UAPSPDIMPDIMRoute
  UAPSPDIMHebdomadaireRoute: typeof UAPSPDIMHebdomadaireRoute
  UAPSPDIMHistoriqueRoute: typeof UAPSPDIMHistoriqueRoute
  UAPSPDIMImporterRoute: typeof UAPSPDIMImporterRoute
  UAPSPDIMJournalierRoute: typeof UAPSPDIMJournalierRoute
  UAPSPDIMModifierRoute: typeof UAPSPDIMModifierRoute
  UAPSPDIMSuivreRoute: typeof UAPSPDIMSuivreRoute
  UAPSPROFILEEPROFILEERoute: typeof UAPSPROFILEEPROFILEERoute
  UAPSPROFILEEHebdomadaireRoute: typeof UAPSPROFILEEHebdomadaireRoute
  UAPSPROFILEEHistoriqueRoute: typeof UAPSPROFILEEHistoriqueRoute
  UAPSPROFILEEImporterRoute: typeof UAPSPROFILEEImporterRoute
  UAPSPROFILEEJournalierRoute: typeof UAPSPROFILEEJournalierRoute
  UAPSPROFILEEModifierRoute: typeof UAPSPROFILEEModifierRoute
  UAPSPROFILEESuivreRoute: typeof UAPSPROFILEESuivreRoute
  UAPSGDIMValidationMatiereRoute: typeof UAPSGDIMValidationMatiereRoute
  UAPSGDIMValidationOutillageRoute: typeof UAPSGDIMValidationOutillageRoute
  UAPSGDIMValidationProductionRoute: typeof UAPSGDIMValidationProductionRoute
  UAPSPDIMValidationMatiereRoute: typeof UAPSPDIMValidationMatiereRoute
  UAPSPDIMValidationOutillageRoute: typeof UAPSPDIMValidationOutillageRoute
  UAPSPDIMValidationProductionRoute: typeof UAPSPDIMValidationProductionRoute
  UAPSPROFILEEValidationMatiereRoute: typeof UAPSPROFILEEValidationMatiereRoute
  UAPSPROFILEEValidationOutillageRoute: typeof UAPSPROFILEEValidationOutillageRoute
  UAPSPROFILEEValidationProductionRoute: typeof UAPSPROFILEEValidationProductionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/page': {
      id: '/login/page'
      path: '/login/page'
      fullPath: '/login/page'
      preLoaderRoute: typeof LoginPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/UAPS': {
      id: '/UAPS/UAPS'
      path: '/UAPS/UAPS'
      fullPath: '/UAPS/UAPS'
      preLoaderRoute: typeof UAPSUAPSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/suivre': {
      id: '/UAPS/PROFILEE/suivre'
      path: '/UAPS/PROFILEE/suivre'
      fullPath: '/UAPS/PROFILEE/suivre'
      preLoaderRoute: typeof UAPSPROFILEESuivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/modifier': {
      id: '/UAPS/PROFILEE/modifier'
      path: '/UAPS/PROFILEE/modifier'
      fullPath: '/UAPS/PROFILEE/modifier'
      preLoaderRoute: typeof UAPSPROFILEEModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/journalier': {
      id: '/UAPS/PROFILEE/journalier'
      path: '/UAPS/PROFILEE/journalier'
      fullPath: '/UAPS/PROFILEE/journalier'
      preLoaderRoute: typeof UAPSPROFILEEJournalierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/importer': {
      id: '/UAPS/PROFILEE/importer'
      path: '/UAPS/PROFILEE/importer'
      fullPath: '/UAPS/PROFILEE/importer'
      preLoaderRoute: typeof UAPSPROFILEEImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/historique': {
      id: '/UAPS/PROFILEE/historique'
      path: '/UAPS/PROFILEE/historique'
      fullPath: '/UAPS/PROFILEE/historique'
      preLoaderRoute: typeof UAPSPROFILEEHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/hebdomadaire': {
      id: '/UAPS/PROFILEE/hebdomadaire'
      path: '/UAPS/PROFILEE/hebdomadaire'
      fullPath: '/UAPS/PROFILEE/hebdomadaire'
      preLoaderRoute: typeof UAPSPROFILEEHebdomadaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/PROFILEE': {
      id: '/UAPS/PROFILEE/PROFILEE'
      path: '/UAPS/PROFILEE/PROFILEE'
      fullPath: '/UAPS/PROFILEE/PROFILEE'
      preLoaderRoute: typeof UAPSPROFILEEPROFILEERouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/suivre': {
      id: '/UAPS/P-DIM/suivre'
      path: '/UAPS/P-DIM/suivre'
      fullPath: '/UAPS/P-DIM/suivre'
      preLoaderRoute: typeof UAPSPDIMSuivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/modifier': {
      id: '/UAPS/P-DIM/modifier'
      path: '/UAPS/P-DIM/modifier'
      fullPath: '/UAPS/P-DIM/modifier'
      preLoaderRoute: typeof UAPSPDIMModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/journalier': {
      id: '/UAPS/P-DIM/journalier'
      path: '/UAPS/P-DIM/journalier'
      fullPath: '/UAPS/P-DIM/journalier'
      preLoaderRoute: typeof UAPSPDIMJournalierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/importer': {
      id: '/UAPS/P-DIM/importer'
      path: '/UAPS/P-DIM/importer'
      fullPath: '/UAPS/P-DIM/importer'
      preLoaderRoute: typeof UAPSPDIMImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/historique': {
      id: '/UAPS/P-DIM/historique'
      path: '/UAPS/P-DIM/historique'
      fullPath: '/UAPS/P-DIM/historique'
      preLoaderRoute: typeof UAPSPDIMHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/hebdomadaire': {
      id: '/UAPS/P-DIM/hebdomadaire'
      path: '/UAPS/P-DIM/hebdomadaire'
      fullPath: '/UAPS/P-DIM/hebdomadaire'
      preLoaderRoute: typeof UAPSPDIMHebdomadaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/P-DIM': {
      id: '/UAPS/P-DIM/P-DIM'
      path: '/UAPS/P-DIM/P-DIM'
      fullPath: '/UAPS/P-DIM/P-DIM'
      preLoaderRoute: typeof UAPSPDIMPDIMRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/suivre': {
      id: '/UAPS/G-DIM/suivre'
      path: '/UAPS/G-DIM/suivre'
      fullPath: '/UAPS/G-DIM/suivre'
      preLoaderRoute: typeof UAPSGDIMSuivreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/modifier': {
      id: '/UAPS/G-DIM/modifier'
      path: '/UAPS/G-DIM/modifier'
      fullPath: '/UAPS/G-DIM/modifier'
      preLoaderRoute: typeof UAPSGDIMModifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/journalier': {
      id: '/UAPS/G-DIM/journalier'
      path: '/UAPS/G-DIM/journalier'
      fullPath: '/UAPS/G-DIM/journalier'
      preLoaderRoute: typeof UAPSGDIMJournalierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/importer': {
      id: '/UAPS/G-DIM/importer'
      path: '/UAPS/G-DIM/importer'
      fullPath: '/UAPS/G-DIM/importer'
      preLoaderRoute: typeof UAPSGDIMImporterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/historique': {
      id: '/UAPS/G-DIM/historique'
      path: '/UAPS/G-DIM/historique'
      fullPath: '/UAPS/G-DIM/historique'
      preLoaderRoute: typeof UAPSGDIMHistoriqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/hebdomadaire': {
      id: '/UAPS/G-DIM/hebdomadaire'
      path: '/UAPS/G-DIM/hebdomadaire'
      fullPath: '/UAPS/G-DIM/hebdomadaire'
      preLoaderRoute: typeof UAPSGDIMHebdomadaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/G-DIM': {
      id: '/UAPS/G-DIM/G-DIM'
      path: '/UAPS/G-DIM/G-DIM'
      fullPath: '/UAPS/G-DIM/G-DIM'
      preLoaderRoute: typeof UAPSGDIMGDIMRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/Validation/production': {
      id: '/UAPS/PROFILEE/Validation/production'
      path: '/UAPS/PROFILEE/Validation/production'
      fullPath: '/UAPS/PROFILEE/Validation/production'
      preLoaderRoute: typeof UAPSPROFILEEValidationProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/Validation/outillage': {
      id: '/UAPS/PROFILEE/Validation/outillage'
      path: '/UAPS/PROFILEE/Validation/outillage'
      fullPath: '/UAPS/PROFILEE/Validation/outillage'
      preLoaderRoute: typeof UAPSPROFILEEValidationOutillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/PROFILEE/Validation/matiere': {
      id: '/UAPS/PROFILEE/Validation/matiere'
      path: '/UAPS/PROFILEE/Validation/matiere'
      fullPath: '/UAPS/PROFILEE/Validation/matiere'
      preLoaderRoute: typeof UAPSPROFILEEValidationMatiereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/Validation/production': {
      id: '/UAPS/P-DIM/Validation/production'
      path: '/UAPS/P-DIM/Validation/production'
      fullPath: '/UAPS/P-DIM/Validation/production'
      preLoaderRoute: typeof UAPSPDIMValidationProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/Validation/outillage': {
      id: '/UAPS/P-DIM/Validation/outillage'
      path: '/UAPS/P-DIM/Validation/outillage'
      fullPath: '/UAPS/P-DIM/Validation/outillage'
      preLoaderRoute: typeof UAPSPDIMValidationOutillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/P-DIM/Validation/matiere': {
      id: '/UAPS/P-DIM/Validation/matiere'
      path: '/UAPS/P-DIM/Validation/matiere'
      fullPath: '/UAPS/P-DIM/Validation/matiere'
      preLoaderRoute: typeof UAPSPDIMValidationMatiereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/Validation/production': {
      id: '/UAPS/G-DIM/Validation/production'
      path: '/UAPS/G-DIM/Validation/production'
      fullPath: '/UAPS/G-DIM/Validation/production'
      preLoaderRoute: typeof UAPSGDIMValidationProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/Validation/outillage': {
      id: '/UAPS/G-DIM/Validation/outillage'
      path: '/UAPS/G-DIM/Validation/outillage'
      fullPath: '/UAPS/G-DIM/Validation/outillage'
      preLoaderRoute: typeof UAPSGDIMValidationOutillageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UAPS/G-DIM/Validation/matiere': {
      id: '/UAPS/G-DIM/Validation/matiere'
      path: '/UAPS/G-DIM/Validation/matiere'
      fullPath: '/UAPS/G-DIM/Validation/matiere'
      preLoaderRoute: typeof UAPSGDIMValidationMatiereRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UAPSUAPSRoute: UAPSUAPSRoute,
  LoginPageRoute: LoginPageRoute,
  UAPSGDIMGDIMRoute: UAPSGDIMGDIMRoute,
  UAPSGDIMHebdomadaireRoute: UAPSGDIMHebdomadaireRoute,
  UAPSGDIMHistoriqueRoute: UAPSGDIMHistoriqueRoute,
  UAPSGDIMImporterRoute: UAPSGDIMImporterRoute,
  UAPSGDIMJournalierRoute: UAPSGDIMJournalierRoute,
  UAPSGDIMModifierRoute: UAPSGDIMModifierRoute,
  UAPSGDIMSuivreRoute: UAPSGDIMSuivreRoute,
  UAPSPDIMPDIMRoute: UAPSPDIMPDIMRoute,
  UAPSPDIMHebdomadaireRoute: UAPSPDIMHebdomadaireRoute,
  UAPSPDIMHistoriqueRoute: UAPSPDIMHistoriqueRoute,
  UAPSPDIMImporterRoute: UAPSPDIMImporterRoute,
  UAPSPDIMJournalierRoute: UAPSPDIMJournalierRoute,
  UAPSPDIMModifierRoute: UAPSPDIMModifierRoute,
  UAPSPDIMSuivreRoute: UAPSPDIMSuivreRoute,
  UAPSPROFILEEPROFILEERoute: UAPSPROFILEEPROFILEERoute,
  UAPSPROFILEEHebdomadaireRoute: UAPSPROFILEEHebdomadaireRoute,
  UAPSPROFILEEHistoriqueRoute: UAPSPROFILEEHistoriqueRoute,
  UAPSPROFILEEImporterRoute: UAPSPROFILEEImporterRoute,
  UAPSPROFILEEJournalierRoute: UAPSPROFILEEJournalierRoute,
  UAPSPROFILEEModifierRoute: UAPSPROFILEEModifierRoute,
  UAPSPROFILEESuivreRoute: UAPSPROFILEESuivreRoute,
  UAPSGDIMValidationMatiereRoute: UAPSGDIMValidationMatiereRoute,
  UAPSGDIMValidationOutillageRoute: UAPSGDIMValidationOutillageRoute,
  UAPSGDIMValidationProductionRoute: UAPSGDIMValidationProductionRoute,
  UAPSPDIMValidationMatiereRoute: UAPSPDIMValidationMatiereRoute,
  UAPSPDIMValidationOutillageRoute: UAPSPDIMValidationOutillageRoute,
  UAPSPDIMValidationProductionRoute: UAPSPDIMValidationProductionRoute,
  UAPSPROFILEEValidationMatiereRoute: UAPSPROFILEEValidationMatiereRoute,
  UAPSPROFILEEValidationOutillageRoute: UAPSPROFILEEValidationOutillageRoute,
  UAPSPROFILEEValidationProductionRoute: UAPSPROFILEEValidationProductionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
